"use client";
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh-CN' | 'zh-TW';

const translations: Record<Language, Record<string, string>> = {
  en: {
    'header.brand': 'Interlectic',
    'header.login': 'Sign In',
    'hero.badge': 'Interlectic Classroom Pro',
    'hero.title': 'The interactive classroom. Reimagined.',
    'hero.subtitle': 'Ultra-low latency dual-way slide synchronization, tactile multi-touch precision, and seamless multi-device collaboration.',
    'hero.loginAsEducator': 'Educator Studio',
    'hero.loginAsStudent': 'Student Portal',
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Manage your courses and students',
    'dashboard.createCourse': 'Create Course',
    'dashboard.yourCourses': 'Your Courses',
    'dashboard.clickToOpen': 'Click to open panel',
    'dashboard.courseExpired': 'Expired',
    'dashboard.published': 'Published',
    'dashboard.close': 'Close',
    'dashboard.editName': 'Edit Name',
    'dashboard.private': 'Private',
    'dashboard.togglePublic': 'Toggle Public/Private',
    'dashboard.openSlides': 'Open Slides',
    'dashboard.logoutStudents': 'Logout Students',
    'dashboard.loginStudents': 'Login Students',
    'dashboard.copyCourse': 'Copy Course',
    'dashboard.enrolledCount': 'Enrolled',
    'dashboard.seatsLeft': 'Seats left',
    'dashboard.sharedWith': 'Shared with',
    'dashboard.connectStudent': 'Connect Student',
    'dashboard.studentEmail': 'Student Email',
    'dashboard.connectBtn': 'Connect',
    'dashboard.bulkImport': 'Bulk Import Students',
    'dashboard.csvFormat': 'CSV Format: name, studentId, email, password, pcId',
    'dashboard.downloadSampleCsv': 'Download Sample CSV',
    'dashboard.uploadBtn': 'Upload CSV',
    'dashboard.rosterTitle': 'Class Roster',
    'dashboard.colName': 'Name',
    'dashboard.colEmail': 'Email',
    'dashboard.colPcId': 'PC ID',
    'dashboard.colStatus': 'Status',
    'dashboard.colActions': 'Actions',
    'sidebar.welcome': 'Welcome back,',
    'sidebar.myCourses': 'My Courses',
    'sidebar.students': 'Students',
    'sidebar.analytics': 'Analytics',
    'sidebar.marketplace': 'Marketplace',
    'sidebar.tokens': 'Buy Tokens',
    'sidebar.educatorShop': 'Educator Shop',
    'sidebar.customOrder': 'Custom Order',
    'sidebar.settings': 'Settings',
    'sidebar.signOut': 'Sign Out',
    'sidebar.documentation': 'Documentation',
    'sidebar.userGuide': 'User Guide',
    'sidebar.userAgreement': 'User Agreement',
    'sidebar.refundPolicy': 'Refund Policy',
    'sidebar.privacyPolicy': 'Privacy Policy',
    'footer.brand': 'Interlectic 聚課',
    'footer.description': 'Interactive learning, intelligent classroom synchronization, and next-generation educational tools.',
    'footer.quickLinks': 'Quick Links',
    'footer.legal': 'Legal & Policies',
    'footer.support': 'Support & Contact',
    'footer.userAgreement': 'User Agreement',
    'footer.refundPolicy': 'Refund Policy',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.userGuide': 'User Guide',
    'footer.rights': 'All rights reserved.',
    'brands.title': 'Trusted & Compatible with Leading Interactive Displays',
    'brands.subtitle': 'Native browser execution · Zero driver installation · Plug and play across all major brands',
    'devices.title': 'Universal Multi-Platform Compatibility',
    'devices.subtitle': 'Seamless real-time synchronization between classroom touchscreens, tablets, PCs, and student devices.',
    'devices.whiteboard': 'Interactive Whiteboards & Displays',
    'devices.whiteboardDesc': 'BenQ, MAXHUB, Seewo, Newline, Promethean, ViewSonic, SMART Board & Huawei IdeaHub',
    'devices.tablets': 'Tablets & Mobile Slates',
    'devices.tabletsDesc': 'iPadOS (Apple Pencil & ProMotion), Android Tablets (Xiaomi/Samsung), Touch Slates',
    'devices.desktops': 'Laptops & Workstations',
    'devices.desktopsDesc': 'Windows 10/11, macOS (MacBook/iMac), ChromeOS & Linux for Education',
    'features.title': 'Engineered for Next-Gen Interactive Classrooms',
    'features.subtitle': 'Modern web technology delivering ultra-low latency, tactile responsiveness, and synchronized instruction.',
    'features.sync.title': 'Zero-Latency Duplex Sync',
    'features.sync.desc': 'Millisecond-level slide flipping, live annotations, and interactive states synchronized across all student screens simultaneously.',
    'features.touch.title': 'Multi-Touch & Stylus Precision',
    'features.touch.desc': 'Optimized for high-resolution digitizers, pressure-sensitive stylus writing, palm rejection, and fluid touch gestures.',
    'features.hardware.title': 'Driver-Free & Web-Native',
    'features.hardware.desc': 'Runs directly inside any modern browser on all interactive screens without installing proprietary software.',
    'features.presence.title': 'Real-Time Presence Tracking',
    'features.presence.desc': 'Teachers gain real-time visibility into student attendance, screen focus, online readiness, and interactive exercise responses.',
  },
  'zh-TW': {
    'header.brand': 'Interlectic',
    'header.login': '登入',
    'hero.badge': 'Interlectic 智慧課堂 · 全新演進',
    'hero.title': '智慧互動課堂。全新境界。',
    'hero.subtitle': '極致毫秒級雙工同步、大屏多點觸控精準交互，為現代教育打造的無感協同體驗。',
    'hero.loginAsEducator': '教師教學入口',
    'hero.loginAsStudent': '學生互動入口',
    'dashboard.title': '控制面板',
    'dashboard.subtitle': '管理您的課程與學生',
    'dashboard.createCourse': '建立課程',
    'dashboard.yourCourses': '您的課程',
    'dashboard.clickToOpen': '點擊展開面板',
    'dashboard.courseExpired': '已過期',
    'dashboard.published': '已發布',
    'dashboard.close': '關閉',
    'dashboard.editName': '編輯名稱',
    'dashboard.private': '私密',
    'dashboard.togglePublic': '切換公開/私密',
    'dashboard.openSlides': '打開課件',
    'dashboard.logoutStudents': '讓學生登出',
    'dashboard.loginStudents': '讓學生登入',
    'dashboard.copyCourse': '複製課程',
    'dashboard.enrolledCount': '已註冊',
    'dashboard.seatsLeft': '剩餘座位',
    'dashboard.sharedWith': '共享給',
    'dashboard.connectStudent': '連接學生',
    'dashboard.studentEmail': '學生電郵',
    'dashboard.connectBtn': '連接',
    'dashboard.bulkImport': '批量導入學生',
    'dashboard.csvFormat': 'CSV 格式: name, studentId, email, password, pcId (姓名, 學號, 電郵, 密碼, PC編號)',
    'dashboard.downloadSampleCsv': '下載範例 CSV',
    'dashboard.uploadBtn': '上傳 CSV',
    'dashboard.rosterTitle': '班級名單',
    'dashboard.colName': '姓名',
    'dashboard.colEmail': '電郵',
    'dashboard.colPcId': '電腦 ID',
    'dashboard.colStatus': '狀態',
    'dashboard.colActions': '操作',
    'sidebar.welcome': '歡迎回來，',
    'sidebar.myCourses': '我的課程',
    'sidebar.students': '學生管理',
    'sidebar.analytics': '數據分析',
    'sidebar.marketplace': '課程市場',
    'sidebar.tokens': '購買代幣',
    'sidebar.educatorShop': '教師商店',
    'sidebar.customOrder': '訂製課程',
    'sidebar.settings': '系統設定',
    'sidebar.signOut': '登出系統',
    'sidebar.documentation': '系統文件',
    'sidebar.userGuide': '使用者指南',
    'sidebar.userAgreement': '用戶協議',
    'sidebar.refundPolicy': '退款政策',
    'sidebar.privacyPolicy': '隱私政策',
    'footer.brand': 'Interlectic 聚課',
    'footer.description': '互動式學習、智慧課堂同步與次世代教育科技平台。',
    'footer.quickLinks': '快速連結',
    'footer.legal': '法律與政策',
    'footer.support': '支援與聯絡',
    'footer.userAgreement': '用戶協議',
    'footer.refundPolicy': '退款政策',
    'footer.privacyPolicy': '隱私政策',
    'footer.userGuide': '使用者指南',
    'footer.rights': '版權所有，保留一切權利。',
    'brands.title': '完美相容主流互動電子白板品牌',
    'brands.subtitle': '原生瀏覽器運行 · 無須安裝驅動程式 · 即插即用適配各大品牌',
    'devices.title': '全平臺與跨設備深度適配',
    'devices.subtitle': '在課堂大屏、平板電腦、筆記型電腦與學生終端之間實現無縫即時同步。',
    'devices.whiteboard': '互動白板與觸控大屏',
    'devices.whiteboardDesc': 'BenQ 明基、MAXHUB、Seewo 希沃、Newline 新線、Promethean 普米、ViewSonic、SMART Board 及華為 IdeaHub',
    'devices.tablets': '平板電腦與行動設備',
    'devices.tabletsDesc': 'iPadOS (支援 Apple Pencil 與 ProMotion)、Android 平板 (小米/三星)、觸控便攜屏',
    'devices.desktops': '筆記型電腦與桌面電腦',
    'devices.desktopsDesc': 'Windows 10/11、macOS (MacBook/iMac)、Chromebook 與 Linux 教育系統',
    'features.title': '專為智慧課堂與協同教學打造',
    'features.subtitle': '結合前沿 Web 技術，提供極致低延遲、細膩觸控與全雙工同步體驗。',
    'features.sync.title': '毫秒級雙工課件同步',
    'features.sync.desc': '即時翻頁廣播、雙向板書標註與頁面狀態全自動同步，學生端毫秒級跟隨。',
    'features.touch.title': '多點觸控與手寫筆優化',
    'features.touch.desc': '深度適配大屏壓感手寫筆與多點觸控手勢，防誤觸演算法確保書寫流暢自然。',
    'features.hardware.title': '無驅動依賴 · 即開即用',
    'features.hardware.desc': '基於現代 Web 技術架構，直接於大屏內建瀏覽器運行，免去安裝專用軟體的繁瑣維護。',
    'features.presence.title': '全端在線狀態與互動感知',
    'features.presence.desc': '教師端即時掌握全班連線狀態、螢幕焦點與隨堂測驗互動反饋，課堂掌控更精準。',
  },
  'zh-CN': {
    'header.brand': 'Interlectic',
    'header.login': '登录',
    'hero.badge': 'Interlectic 智慧课堂 · 全新演进',
    'hero.title': '智慧互动课堂。全新境界。',
    'hero.subtitle': '极致毫秒级双工同步、大屏多点触控精准交互，为现代教育打造的无感协同体验。',
    'hero.loginAsEducator': '教师教学入口',
    'hero.loginAsStudent': '学生互动入口',
    'dashboard.title': '控制面板',
    'dashboard.subtitle': '管理您的课程与学生',
    'dashboard.createCourse': '创建课程',
    'dashboard.yourCourses': '您的课程',
    'dashboard.clickToOpen': '点击展开面板',
    'dashboard.courseExpired': '已过期',
    'dashboard.published': '已发布',
    'dashboard.close': '关闭',
    'dashboard.editName': '编辑名称',
    'dashboard.private': '私密',
    'dashboard.togglePublic': '切换公开/私密',
    'dashboard.openSlides': '打开课件',
    'dashboard.logoutStudents': '让学生登出',
    'dashboard.loginStudents': '让学生登入',
    'dashboard.copyCourse': '复制课程',
    'dashboard.enrolledCount': '已注册',
    'dashboard.seatsLeft': '剩余座位',
    'dashboard.sharedWith': '共享给',
    'dashboard.connectStudent': '连接学生',
    'dashboard.studentEmail': '学生邮箱',
    'dashboard.connectBtn': '连接',
    'dashboard.bulkImport': '批量导入学生',
    'dashboard.csvFormat': 'CSV 格式: name, studentId, email, password, pcId (姓名, 学号, 邮箱, 密码, PC编号)',
    'dashboard.downloadSampleCsv': '下载示例 CSV',
    'dashboard.uploadBtn': '上传 CSV',
    'dashboard.rosterTitle': '班级名单',
    'dashboard.colName': '姓名',
    'dashboard.colEmail': '邮箱',
    'dashboard.colPcId': '电脑 ID',
    'dashboard.colStatus': '状态',
    'dashboard.colActions': '操作',
    'sidebar.welcome': '欢迎回来，',
    'sidebar.myCourses': '我的课程',
    'sidebar.students': '学生管理',
    'sidebar.analytics': '数据分析',
    'sidebar.marketplace': '课程市场',
    'sidebar.tokens': '购买代币',
    'sidebar.educatorShop': '教师商店',
    'sidebar.customOrder': '定制课程',
    'sidebar.settings': '系统设置',
    'sidebar.signOut': '退出系统',
    'sidebar.documentation': '系统文档',
    'sidebar.userGuide': '用户指南',
    'sidebar.userAgreement': '用户协议',
    'sidebar.refundPolicy': '退款政策',
    'sidebar.privacyPolicy': '隐私政策',
    'footer.brand': 'Interlectic 聚課',
    'footer.description': '互动式学习、智慧课堂同步与次世代教育科技平台。',
    'footer.quickLinks': '快速链接',
    'footer.legal': '法律与政策',
    'footer.support': '支持与联系',
    'footer.userAgreement': '用户协议',
    'footer.refundPolicy': '退款政策',
    'footer.privacyPolicy': '隐私政策',
    'footer.userGuide': '用户指南',
    'footer.rights': '版权所有，保留一切权利。',
    'brands.title': '完美兼容主流交互电子白板品牌',
    'brands.subtitle': '原生浏览器运行 · 无须安装驱动程序 · 即插即用适配各大品牌',
    'devices.title': '全平台与跨设备深度适配',
    'devices.subtitle': '在课堂大屏、平板电脑、笔记本电脑与学生终端之间实现无缝实时同步。',
    'devices.whiteboard': '交互白板与触控大屏',
    'devices.whiteboardDesc': 'BenQ 明基、MAXHUB、Seewo 希沃、Newline 新线、Promethean 普米、ViewSonic、SMART Board 及华为 IdeaHub',
    'devices.tablets': '平板电脑与移动设备',
    'devices.tabletsDesc': 'iPadOS (支持 Apple Pencil 与 ProMotion)、Android 平板 (小米/三星)、触控便携屏',
    'devices.desktops': '笔记本电脑与桌面电脑',
    'devices.desktopsDesc': 'Windows 10/11、macOS (MacBook/iMac)、Chromebook 与 Linux 教育系统',
    'features.title': '专为智慧课堂与协同教学打造',
    'features.subtitle': '结合前沿 Web 技术，提供极致低延迟、细腻触控与全双工同步体验。',
    'features.sync.title': '毫秒级双工课件同步',
    'features.sync.desc': '实时翻页广播、双向板书标注与页面状态全自动同步，学生端毫秒级跟随。',
    'features.touch.title': '多点触控与手写笔优化',
    'features.touch.desc': '深度适配大屏压感手写笔与多点触控手势，防误触算法确保书写流畅自然。',
    'features.hardware.title': '无驱动依赖 · 即开即用',
    'features.hardware.desc': '基于现代 Web 技术架构，直接于大屏内置浏览器运行，免去安装专用软件的繁琐维护。',
    'features.presence.title': '全端在线状态与互动感知',
    'features.presence.desc': '教师端实时掌握全班连接状态、屏幕焦点与随堂测验互动反馈，课堂掌控更精准。',
  }
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
